In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df=pd.read_csv("customers (1).csv")

In [3]:
df

     customer_id  gender  age        city signup_date loyalty_member
0          C0001    Male   19   Liverpool  2023-10-17            Yes
1          C0002    Male   65  Manchester  2022-08-17            Yes
2          C0003  Female   20      London  2023-08-28            Yes
3          C0004    Male   50      London  2022-08-12            Yes
4          C0005  Female   32  Nottingham  2023-10-28             No
...          ...     ...  ...         ...         ...            ...
1195       C1196  Female   20      London  2023-02-25             No
1196       C1197    Male   55  Nottingham  2023-01-13            Yes
1197       C1198  Female   47  Manchester  2022-05-26            Yes
1198       C1199  Female   58  Manchester  2022-09-09             No
1199       C1200    Male   39      London  2023-09-20             No

[1200 rows x 6 columns]

In [4]:
df = pd.get_dummies(df,columns=["city"],drop_first=True,dtype=int)

In [5]:
df

,customer_id,gender,age,signup_date,loyalty_member,city_Bristol,city_Leeds,city_Liverpool,city_London,city_Manchester,city_Nottingham,city_Sheffield
0,C0001,Male,19,2023-10-17,Yes,0,0,1,0,0,0,0
1,C0002,Male,65,2022-08-17,Yes,0,0,0,0,1,0,0
2,C0003,Female,20,2023-08-28,Yes,0,0,0,1,0,0,0
3,C0004,Male,50,2022-08-12,Yes,0,0,0,1,0,0,0
4,C0005,Female,32,2023-10-28,No,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,C1196,Female,20,2023-02-25,No,0,0,0,1,0,0,0
1196,C1197,Male,55,2023-01-13,Yes,0,0,0,0,0,1,0
1197,C1198,Female,47,2022-05-26,Yes,0,0,0,0,1,0,0
1198,C1199,Female,58,2022-09-09,No,0,0,0,0,1,0,0
1199,C1200,Male,39,2023-09-20,No,0,0,0,1,0,0,0

In [6]:
df["loyalty_member"]=df["loyalty_member"].replace({"Yes":0,"No":1})

In [7]:
df

,customer_id,gender,age,signup_date,loyalty_member,city_Bristol,city_Leeds,city_Liverpool,city_London,city_Manchester,city_Nottingham,city_Sheffield
0,C0001,Male,19,2023-10-17,0,0,0,1,0,0,0,0
1,C0002,Male,65,2022-08-17,0,0,0,0,0,1,0,0
2,C0003,Female,20,2023-08-28,0,0,0,0,1,0,0,0
3,C0004,Male,50,2022-08-12,0,0,0,0,1,0,0,0
4,C0005,Female,32,2023-10-28,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,C1196,Female,20,2023-02-25,1,0,0,0,1,0,0,0
1196,C1197,Male,55,2023-01-13,0,0,0,0,0,0,1,0
1197,C1198,Female,47,2022-05-26,0,0,0,0,0,1,0,0
1198,C1199,Female,58,2022-09-09,1,0,0,0,0,1,0,0
1199,C1200,Male,39,2023-09-20,1,0,0,0,1,0,0,0

In [8]:
df["gender"]=df["gender"].replace({"Male":0,"Female":1})

df

# Featurte Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
df1=['age']
scaler=StandardScaler()

df[df1]=scaler.fit_transform(df[df1])

In [12]:
df

,customer_id,gender,age,signup_date,loyalty_member,city_Bristol,city_Leeds,city_Liverpool,city_London,city_Manchester,city_Nottingham,city_Sheffield
0,C0001,0,-1.649130,2023-10-17,0,0,0,1,0,0,0,0
1,C0002,0,1.705156,2022-08-17,0,0,0,0,0,1,0,0
2,C0003,1,-1.576211,2023-08-28,0,0,0,0,1,0,0,0
3,C0004,0,0.611367,2022-08-12,0,0,0,0,1,0,0,0
4,C0005,1,-0.701179,2023-10-28,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,C1196,1,-1.576211,2023-02-25,1,0,0,0,1,0,0,0
1196,C1197,0,0.975964,2023-01-13,0,0,0,0,0,0,1,0
1197,C1198,1,0.392609,2022-05-26,0,0,0,0,0,1,0,0
1198,C1199,1,1.194721,2022-09-09,1,0,0,0,0,1,0,0
1199,C1200,0,-0.190745,2023-09-20,1,0,0,0,1,0,0,0

In [20]:
df.drop('customer_id', axis=1, inplace=True)

In [21]:
df

,gender,age,signup_date,loyalty_member,city_Bristol,city_Leeds,city_Liverpool,city_London,city_Manchester,city_Nottingham,city_Sheffield
0,0,-1.649130,2023-10-17,0,0,0,1,0,0,0,0
1,0,1.705156,2022-08-17,0,0,0,0,0,1,0,0
2,1,-1.576211,2023-08-28,0,0,0,0,1,0,0,0
3,0,0.611367,2022-08-12,0,0,0,0,1,0,0,0
4,1,-0.701179,2023-10-28,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
1195,1,-1.576211,2023-02-25,1,0,0,0,1,0,0,0
1196,0,0.975964,2023-01-13,0,0,0,0,0,0,1,0
1197,1,0.392609,2022-05-26,0,0,0,0,0,1,0,0
1198,1,1.194721,2022-09-09,1,0,0,0,0,1,0,0
1199,0,-0.190745,2023-09-20,1,0,0,0,1,0,0,0

In [22]:
df["signup_date"].dtype

In [23]:
df['signup_date'] = pd.to_datetime(df['signup_date'])

In [25]:
df["signup_date"].dtype

dtype('<M8[us]')

# Feature Extraction

In [26]:
df['signup_year'] = df['signup_date'].dt.year
df['signup_month'] = df['signup_date'].dt.month
df['signup_day'] = df['signup_date'].dt.day

In [27]:
df

,gender,age,signup_date,loyalty_member,city_Bristol,city_Leeds,city_Liverpool,city_London,city_Manchester,city_Nottingham,city_Sheffield,signup_year,signup_month,signup_day
0,0,-1.649130,2023-10-17,0,0,0,1,0,0,0,0,2023,10,17
1,0,1.705156,2022-08-17,0,0,0,0,0,1,0,0,2022,8,17
2,1,-1.576211,2023-08-28,0,0,0,0,1,0,0,0,2023,8,28
3,0,0.611367,2022-08-12,0,0,0,0,1,0,0,0,2022,8,12
4,1,-0.701179,2023-10-28,1,0,0,0,0,0,1,0,2023,10,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1,-1.576211,2023-02-25,1,0,0,0,1,0,0,0,2023,2,25
1196,0,0.975964,2023-01-13,0,0,0,0,0,0,1,0,2023,1,13
1197,1,0.392609,2022-05-26,0,0,0,0,0,1,0,0,2022,5,26
1198,1,1.194721,2022-09-09,1,0,0,0,0,1,0,0,2022,9,9
1199,0,-0.190745,2023-09-20,1,0,0,0,1,0,0,0,2023,9,20

In [31]:
df.drop("signup_date",inplace=True,axis=1)

In [32]:
df

,gender,age,loyalty_member,city_Bristol,city_Leeds,city_Liverpool,city_London,city_Manchester,city_Nottingham,city_Sheffield,signup_year,signup_month,signup_day
0,0,-1.649130,0,0,0,1,0,0,0,0,2023,10,17
1,0,1.705156,0,0,0,0,0,1,0,0,2022,8,17
2,1,-1.576211,0,0,0,0,1,0,0,0,2023,8,28
3,0,0.611367,0,0,0,0,1,0,0,0,2022,8,12
4,1,-0.701179,1,0,0,0,0,0,1,0,2023,10,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1,-1.576211,1,0,0,0,1,0,0,0,2023,2,25
1196,0,0.975964,0,0,0,0,0,0,1,0,2023,1,13
1197,1,0.392609,0,0,0,0,0,1,0,0,2022,5,26
1198,1,1.194721,1,0,0,0,0,1,0,0,2022,9,9
1199,0,-0.190745,1,0,0,0,1,0,0,0,2023,9,20